version: '3'

tasks:
  start-consumer:
    cmds:
      - go run ./kafka-consumer/consumer/main.go

  start-producer:
    cmds:
      - go run ./kafka-producer/producer/main.go

  bench-cpu-consumer:
    cmds:
      - go test -bench . -benchmem -cpuprofile prof.cpu ./kafka-consumer/consumer

  pprof-cpu:
    cmds:
      - go tool pprof consumer.test prof.cpu

  pprof-cpu-web:
    cmds:
      - go tool pprof -http=:8080 prof.cpu

  bench-mem-consumer:
    cmds:
      - go test -bench . -benchmem -memprofile prof.mem ./kafka-consumer/consumer

  pprof-mem:
    cmds:
      - go tool pprof consumer.test prof.mem

  pprof-mem-web:
    cmds:
      - go tool pprof -http=:8080 prof.mem